---
title: "1_Strings"
author: "RRPS"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval=FALSE, 
                      message=FALSE, 
                      warning=FALSE)
```

#1. Numbers

## Math operations
```{python}
1+3
1 / 7
2 ** 3
```

## Mod operator
Check if there is a remainder
```{python}
50 % 5
20 % 2
21 % 5
```

# Variable assignment
```{python}
a = 10
a


b = 15
b
```

```{python}
a + b
```

## types
```{python}
a = 30
type(a)

a = 30.1
type(a)

```


#2. Strings

Different from R and other languages, python index starts with 0
```{python}
"hello"
print("Hello World")
```

## Scape sequences
```{python}
print("Hello \n World") # new line
print("Hello \tWorld") # tab
```

## Length function

Count the space
```{python}
len("I am")
```

## Indexing

Starts with 0
```{python}
my_string="Hello World"
my_string[0]

my_string[9]
my_string[-3]
# the last word
my_string[-1]
```

## Slicing

Subset string
string[start;end;step]
step means jumping
```{python}
my_string="abcdefghijk"

# ":" up tp but not included 
my_string[2:]
# frm the beginning up to the 3 position, but nt inlcuding the 3 position
my_string[:3]
my_string[3:6]
# everything but the last word
my_string[:-1]

# step
# from the beginning jumping 3 indexes
my_string[::3]
my_string[2:7:2]

# reverse the string
my_string[::-1]
```

## Immutability
```{python}
name = "Sam"
name
# can't change by indexing
name[0] = "P"

# we need by concatenating strings
last_letters = "am"
'P' + last_letters
```

String concatenation

```{python}
x = "Hello World"
x + ' is beautiful outside'

one_letter = "a"
one_letter * 10

# dynamic typing
2 + 3
"2" + '5'
```


## Methods

### Formating

press dot and then tab to see the methods availble of the data type
```{python}
x = 'Hello World'
# press dot and then tab to see the methods availble of the data type
x.lower()
x.upper()
x.split() # split a list based on white space
x.split("o") # by the letter 'o'
```

#### Formating with placeholders `%`

The oldest method 

Use `%s` to inject strings. It cnverst everything into string format
The `%d` modulo inserts numbers without rounding

```{python}
print("I'm going to inject %s here." %'something')

# more strings
print("I'm going to inject %s text here, and %s text here." %('some','more'))

# %s and %d
print('I wrote %s programs today.' %3.75)
print('I wrote %d programs today.' %3.75) 
```


The `%r` abd `%s` methods converts any python object to a string using two methods. 

- The `repr()` function returns a printable representation of the given object.
- The `str()` function converts values to a string form 

```{python}
print('He said his name was %s.' %'Fred')
print('He said his name was %r.' %'Fred')

print('He said his name was %s.' %2.45)
print('He said his name was %r.' %2.45)

print('I once caught a fish %s.' %'this \tbig')
print('I once caught a fish %r.' %'this \tbig')
```

Using floating numbers

`{valeu:width.precision f}`

width = would be the minimum number of characters the string should contain
precision = round the number (decimal)

```{python}
print('Floating point numbers: %5.2f' %(19.144983743289472839))
```

Multiple formatting

```{python}
print('First: %s, Second: %5.2f, Third: %r' %('hi!',3.1415,'bye!'))
```


#### `.format()` method for printing

An improved technique

The `.format()` is something like this
"You can put a string here `{}` and the put another here `{}`".format('something1', 'something2')

```{python}
# Insert by index position
print("You can put a string here {} and the put another here {}".format('some1', 'some2'))

print("The {} {} {}".format('fox', 'white','red'))

# by variable assignment
print("The {a} {b} {b}".format(a='fox', b='white',c='red'))
```

Float formatting

`{valeu:width.precision f}`

width = would be the minimum number of characters the string should contain
precision = round the number (decimal)
```{python}
result = 100/777
result

print("The result is {r}".format(r=result))

print("The result is {r:1.3f}".format(r=result))

result = 104.12345
print("The result is {r:1.3f}".format(r=result))
print("The result is {r:10.3f}".format(r=result))
print("The result is {r:15.3f}".format(r=result))
print("The result is {r:20.3f}".format(r=result))
```

#### [f-string method](https://docs.python.org/3/reference/lexical_analysis.html#f-strings)

new method, after Python 3.6

```{python}
name = "Jose"
print(f'Hello, my name is {name}')

age = 34
print(f'Hello, my name is {name}, I am {age} years old')

# string representation (!r)
print(f"He said his name is {name!r}")
f"He said his name is {repr(name)}."

```

Float formatting follows 

`"result: {value:{width}.{precision}}"`

```{python}
num = 23.45678
# print("My 10 character, four decimal number is:{0:10.4f}".format(num))
print(f"My 10 character, four decimal number is:{num:{10}.{6}}")
# or
print(f"My 10 character, four decimal number is:{num:10.4f}")
```

Date and time format

```{python}
today = datetime(year=2017, month=1, day=27)
```

