---
title: "Tuples"
author: "RRPS"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval=FALSE, 
                      message=FALSE, 
                      warning=FALSE)
```

#1. Tuples

Very similar to lists, but they are immutable.
Tuples use parenthesis.

Tuples are useful when you want to code and avoid changes and mistakes.

```{python}
# Create a tuple
t = (1,2,3)

t = (1,2,[1,2])

t

type(t)
```


```{python}
# Create a list
l = [1,2,3]

type(l)
```

Same as list, you can mix objects and use indexing
```{python}
# Can also mix object types
t = ("one",3)

t[0]

t[-1]
```

Tuple Methods
```{python}
t = ('a', 'a', 'one' ,'a', 'a', 'a')

# Use .count to count the number of times a value appears
t.count('a')
# Use .index to enter a value and return the index
t.index('one')

```

Immuatability

This makes tuple be diffrent from lists
```{python}
t[0]= 'change'

t
```

#2. Sets

Sets are an unordered collection of **unique** elements. We can construct them by using the set() function. Let's go ahead and make a set to see how it works.

```{python}
myset = set()

myset
```

```{python}
# We add to sets with the add() method
myset.add(1)

myset
```

It has brackets, but it is not a dictionary because there is no key value pair.

```{python}
# We add to sets with the add() method
myset.add(2)

myset

```

Add 2 a second time
```{python}
# try add 2 again
myset.add(2)

myset
```

Only accept unique values.

```{python}
# Create a list with repeats
mylist = [1,1,2,2,3,4,5,6,1,1]

# cast this as a set
set(mylist)

set("Mississippi")
```

3. Booleans

Python comes with Booleans (with predefined True and False displays that are basically just the integers 1 and 0).

```{python}
a = True

a
```

Make comparisons
```{python}
1 > 3
```

We can use None as a placeholder for an object that we don't want to reassign yet:

```{python}
b= None

b

print(b)
```

