---
title: "files"
author: "RRPS"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval=FALSE, 
                      message=FALSE, 
                      warning=FALSE)
```

#1. Files

## Text files

The `%%` only work in jupyter notebook

```{python}
# Create a tuple
%%writefile myfile.txt
Hello this is a text file
this is the second line
this is the third line

```

```{python}
# check the location
myfile = open('C:/Users/rrocha/Documents/R/python_basics/myfile.txt')
```

read the file
```{python}
myfile.read()

# But what happens if we try to read it again?
myfile.read()
```

This happens because you can imagine the reading "cursor" is at the end of the file after having read it. So there is nothing left to read. We can reset the "cursor" like this:

You need to do this every time :(

```{python}
# Seek to the start of file (index 0)
myfile.seek(0)

# Now read again
myfile.readlines()
```

When you have finished using a file, it is always good practice to close it.

```{python}
myfile.close()
```

To avoid errors in close()

There is another alternative. So it's good practice to use a `with` block.

```{python}
with open('C:/Users/rrocha/Documents/R/python_basics/myfile.txt') as my_new_file:
  contents = my_new_file.read()
```

```{python}
contents
```


## Writing to a File

Opening a file with `'w'` or `'w+'` truncates the original, meaning that anything that was in the original file is deleted!

The default .

### Reading, Writing, Appending Modes

- `mode = "r"` = read only
- `mode = "w"` = write only (overwrites or creates new!)
- `mode = "a"` = append only (will add on to files)
- `mode = "a+"` = read and append (will add on to files)
- `mode = "r+"` = reading and writing
- `mode = "w+"` = writing and reading (overwrites existing files or creates new files). If the file does not exist, one will be created.

```{python}
myfile = open('C:/Users/rrocha/Documents/R/python_basics/myfile.txt')
```

```{python}
with open(myfile, mode = 'r') as f:
  print(f.read())
```

```{python}
with open (myfile, mode = "a") as f:
  f.write("\nanother line")
```

```{python}
with open(myfile, mode = 'r') as f:
  print(f.read())
```

```{python}
with open("new_file_1.txt", mode = 'w') as f:
  f.write("I created this new file")
```


```{python}
with open(myfile, mode = 'r') as f:
  print(f.read())
```


Resources for More Basic Practice
Before you begin your assessment, I wanted to point out some helpful links for practice (don't worry about being able to do these exercises, I just want you to be aware of the links so you can visit them later, since we still haven't discussed functions, you won't be able to utilize a lot of these resources yet!):

Basic Practice:

http://codingbat.com/python

More Mathematical (and Harder) Practice:

https://projecteuler.net/archives

List of Practice Problems:

http://www.codeabbey.com/index/task_list

A SubReddit Devoted to Daily Practice Problems:

https://www.reddit.com/r/dailyprogrammer

A very tricky website with very few hints and touch problems (Not for beginners but still interesting)